import type { Metadata } from "next";
import "./ui/globals.css";
import { inter } from "./ui/fonts";
import Sidenav from "./ui/sidenav/Sidenav";

export const metadata: Metadata = {
  title: "Valentine Stocks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialised`}>
        <div className="flex min-h-screen">
          <Sidenav />
          <div className="flex-1 p-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
